services:
  pg0:
    image: postgres:15
    container_name: pg0
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg01_data:/var/lib/postgresql/data
  pg1:
    image: postgres:15
    container_name: pg1
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - pg02_data:/var/lib/postgresql/data
  pg2:
    image: postgres:15
    container_name: pg2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - pg03_data:/var/lib/postgresql/data
  pg3:
    image: postgres:15
    container_name: pg3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - pg04_data:/var/lib/postgresql/data

volumes:
  pg01_data:
  pg02_data:
  pg03_data:
  pg04_data:
